### ISSUE TITLE
When will there be cunthook catbot-setup?

### ISSUE THREAD

**Issue by russellcrowe-xpaha** [BlueSnoopT/Cunthook#1]

**Comment by BlueSnoopT** [comment]
if you have c++ experience you could just change file paths to run it on catbot-setup, but if you wanted to wait then it will probably be uploaded in a day or 2. Ill send a message here again when its uploaded and link it.

**Comment by BlueSnoopT** [comment]
@russellcrowe-xpaha here you go [Cuntbot](https://github.com/BlueSnoopT/Cuntbot), it may not work because I'm still doing stuff to it. But if you find issues send an issue report there for it. have fun!
